# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/eli/Documents/source/repos/Pegasus

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/eli/Documents/source/repos/Pegasus

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eli/Documents/source/repos/Pegasus/CMakeFiles /home/eli/Documents/source/repos/Pegasus//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eli/Documents/source/repos/Pegasus/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Pegasus

# Build rule for target.
Pegasus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Pegasus
.PHONY : Pegasus

# fast build rule for target.
Pegasus/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/build
.PHONY : Pegasus/fast

src/BattleGUI.o: src/BattleGUI.cpp.o
.PHONY : src/BattleGUI.o

# target to build an object file
src/BattleGUI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/BattleGUI.cpp.o
.PHONY : src/BattleGUI.cpp.o

src/BattleGUI.i: src/BattleGUI.cpp.i
.PHONY : src/BattleGUI.i

# target to preprocess a source file
src/BattleGUI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/BattleGUI.cpp.i
.PHONY : src/BattleGUI.cpp.i

src/BattleGUI.s: src/BattleGUI.cpp.s
.PHONY : src/BattleGUI.s

# target to generate assembly for a file
src/BattleGUI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/BattleGUI.cpp.s
.PHONY : src/BattleGUI.cpp.s

src/BattleState.o: src/BattleState.cpp.o
.PHONY : src/BattleState.o

# target to build an object file
src/BattleState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/BattleState.cpp.o
.PHONY : src/BattleState.cpp.o

src/BattleState.i: src/BattleState.cpp.i
.PHONY : src/BattleState.i

# target to preprocess a source file
src/BattleState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/BattleState.cpp.i
.PHONY : src/BattleState.cpp.i

src/BattleState.s: src/BattleState.cpp.s
.PHONY : src/BattleState.s

# target to generate assembly for a file
src/BattleState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/BattleState.cpp.s
.PHONY : src/BattleState.cpp.s

src/Blerb.o: src/Blerb.cpp.o
.PHONY : src/Blerb.o

# target to build an object file
src/Blerb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Blerb.cpp.o
.PHONY : src/Blerb.cpp.o

src/Blerb.i: src/Blerb.cpp.i
.PHONY : src/Blerb.i

# target to preprocess a source file
src/Blerb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Blerb.cpp.i
.PHONY : src/Blerb.cpp.i

src/Blerb.s: src/Blerb.cpp.s
.PHONY : src/Blerb.s

# target to generate assembly for a file
src/Blerb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Blerb.cpp.s
.PHONY : src/Blerb.cpp.s

src/Blrb.o: src/Blrb.cpp.o
.PHONY : src/Blrb.o

# target to build an object file
src/Blrb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Blrb.cpp.o
.PHONY : src/Blrb.cpp.o

src/Blrb.i: src/Blrb.cpp.i
.PHONY : src/Blrb.i

# target to preprocess a source file
src/Blrb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Blrb.cpp.i
.PHONY : src/Blrb.cpp.i

src/Blrb.s: src/Blrb.cpp.s
.PHONY : src/Blrb.s

# target to generate assembly for a file
src/Blrb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Blrb.cpp.s
.PHONY : src/Blrb.cpp.s

src/CharacterEditorState.o: src/CharacterEditorState.cpp.o
.PHONY : src/CharacterEditorState.o

# target to build an object file
src/CharacterEditorState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/CharacterEditorState.cpp.o
.PHONY : src/CharacterEditorState.cpp.o

src/CharacterEditorState.i: src/CharacterEditorState.cpp.i
.PHONY : src/CharacterEditorState.i

# target to preprocess a source file
src/CharacterEditorState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/CharacterEditorState.cpp.i
.PHONY : src/CharacterEditorState.cpp.i

src/CharacterEditorState.s: src/CharacterEditorState.cpp.s
.PHONY : src/CharacterEditorState.s

# target to generate assembly for a file
src/CharacterEditorState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/CharacterEditorState.cpp.s
.PHONY : src/CharacterEditorState.cpp.s

src/CharacterTab.o: src/CharacterTab.cpp.o
.PHONY : src/CharacterTab.o

# target to build an object file
src/CharacterTab.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/CharacterTab.cpp.o
.PHONY : src/CharacterTab.cpp.o

src/CharacterTab.i: src/CharacterTab.cpp.i
.PHONY : src/CharacterTab.i

# target to preprocess a source file
src/CharacterTab.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/CharacterTab.cpp.i
.PHONY : src/CharacterTab.cpp.i

src/CharacterTab.s: src/CharacterTab.cpp.s
.PHONY : src/CharacterTab.s

# target to generate assembly for a file
src/CharacterTab.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/CharacterTab.cpp.s
.PHONY : src/CharacterTab.cpp.s

src/DefaultMode.o: src/DefaultMode.cpp.o
.PHONY : src/DefaultMode.o

# target to build an object file
src/DefaultMode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/DefaultMode.cpp.o
.PHONY : src/DefaultMode.cpp.o

src/DefaultMode.i: src/DefaultMode.cpp.i
.PHONY : src/DefaultMode.i

# target to preprocess a source file
src/DefaultMode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/DefaultMode.cpp.i
.PHONY : src/DefaultMode.cpp.i

src/DefaultMode.s: src/DefaultMode.cpp.s
.PHONY : src/DefaultMode.s

# target to generate assembly for a file
src/DefaultMode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/DefaultMode.cpp.s
.PHONY : src/DefaultMode.cpp.s

src/DialougeSystem.o: src/DialougeSystem.cpp.o
.PHONY : src/DialougeSystem.o

# target to build an object file
src/DialougeSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/DialougeSystem.cpp.o
.PHONY : src/DialougeSystem.cpp.o

src/DialougeSystem.i: src/DialougeSystem.cpp.i
.PHONY : src/DialougeSystem.i

# target to preprocess a source file
src/DialougeSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/DialougeSystem.cpp.i
.PHONY : src/DialougeSystem.cpp.i

src/DialougeSystem.s: src/DialougeSystem.cpp.s
.PHONY : src/DialougeSystem.s

# target to generate assembly for a file
src/DialougeSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/DialougeSystem.cpp.s
.PHONY : src/DialougeSystem.cpp.s

src/EditorModes.o: src/EditorModes.cpp.o
.PHONY : src/EditorModes.o

# target to build an object file
src/EditorModes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/EditorModes.cpp.o
.PHONY : src/EditorModes.cpp.o

src/EditorModes.i: src/EditorModes.cpp.i
.PHONY : src/EditorModes.i

# target to preprocess a source file
src/EditorModes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/EditorModes.cpp.i
.PHONY : src/EditorModes.cpp.i

src/EditorModes.s: src/EditorModes.cpp.s
.PHONY : src/EditorModes.s

# target to generate assembly for a file
src/EditorModes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/EditorModes.cpp.s
.PHONY : src/EditorModes.cpp.s

src/EditorState.o: src/EditorState.cpp.o
.PHONY : src/EditorState.o

# target to build an object file
src/EditorState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/EditorState.cpp.o
.PHONY : src/EditorState.cpp.o

src/EditorState.i: src/EditorState.cpp.i
.PHONY : src/EditorState.i

# target to preprocess a source file
src/EditorState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/EditorState.cpp.i
.PHONY : src/EditorState.cpp.i

src/EditorState.s: src/EditorState.cpp.s
.PHONY : src/EditorState.s

# target to generate assembly for a file
src/EditorState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/EditorState.cpp.s
.PHONY : src/EditorState.cpp.s

src/Enemy.o: src/Enemy.cpp.o
.PHONY : src/Enemy.o

# target to build an object file
src/Enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Enemy.cpp.o
.PHONY : src/Enemy.cpp.o

src/Enemy.i: src/Enemy.cpp.i
.PHONY : src/Enemy.i

# target to preprocess a source file
src/Enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Enemy.cpp.i
.PHONY : src/Enemy.cpp.i

src/Enemy.s: src/Enemy.cpp.s
.PHONY : src/Enemy.s

# target to generate assembly for a file
src/Enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Enemy.cpp.s
.PHONY : src/Enemy.cpp.s

src/EnemyEditorMode.o: src/EnemyEditorMode.cpp.o
.PHONY : src/EnemyEditorMode.o

# target to build an object file
src/EnemyEditorMode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/EnemyEditorMode.cpp.o
.PHONY : src/EnemyEditorMode.cpp.o

src/EnemyEditorMode.i: src/EnemyEditorMode.cpp.i
.PHONY : src/EnemyEditorMode.i

# target to preprocess a source file
src/EnemyEditorMode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/EnemyEditorMode.cpp.i
.PHONY : src/EnemyEditorMode.cpp.i

src/EnemyEditorMode.s: src/EnemyEditorMode.cpp.s
.PHONY : src/EnemyEditorMode.s

# target to generate assembly for a file
src/EnemyEditorMode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/EnemyEditorMode.cpp.s
.PHONY : src/EnemyEditorMode.cpp.s

src/EnemySpawner.o: src/EnemySpawner.cpp.o
.PHONY : src/EnemySpawner.o

# target to build an object file
src/EnemySpawner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/EnemySpawner.cpp.o
.PHONY : src/EnemySpawner.cpp.o

src/EnemySpawner.i: src/EnemySpawner.cpp.i
.PHONY : src/EnemySpawner.i

# target to preprocess a source file
src/EnemySpawner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/EnemySpawner.cpp.i
.PHONY : src/EnemySpawner.cpp.i

src/EnemySpawner.s: src/EnemySpawner.cpp.s
.PHONY : src/EnemySpawner.s

# target to generate assembly for a file
src/EnemySpawner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/EnemySpawner.cpp.s
.PHONY : src/EnemySpawner.cpp.s

src/EnemySystem.o: src/EnemySystem.cpp.o
.PHONY : src/EnemySystem.o

# target to build an object file
src/EnemySystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/EnemySystem.cpp.o
.PHONY : src/EnemySystem.cpp.o

src/EnemySystem.i: src/EnemySystem.cpp.i
.PHONY : src/EnemySystem.i

# target to preprocess a source file
src/EnemySystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/EnemySystem.cpp.i
.PHONY : src/EnemySystem.cpp.i

src/EnemySystem.s: src/EnemySystem.cpp.s
.PHONY : src/EnemySystem.s

# target to generate assembly for a file
src/EnemySystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/EnemySystem.cpp.s
.PHONY : src/EnemySystem.cpp.s

src/Entity.o: src/Entity.cpp.o
.PHONY : src/Entity.o

# target to build an object file
src/Entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Entity.cpp.o
.PHONY : src/Entity.cpp.o

src/Entity.i: src/Entity.cpp.i
.PHONY : src/Entity.i

# target to preprocess a source file
src/Entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Entity.cpp.i
.PHONY : src/Entity.cpp.i

src/Entity.s: src/Entity.cpp.s
.PHONY : src/Entity.s

# target to generate assembly for a file
src/Entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Entity.cpp.s
.PHONY : src/Entity.cpp.s

src/EnviornmentalMode.o: src/EnviornmentalMode.cpp.o
.PHONY : src/EnviornmentalMode.o

# target to build an object file
src/EnviornmentalMode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/EnviornmentalMode.cpp.o
.PHONY : src/EnviornmentalMode.cpp.o

src/EnviornmentalMode.i: src/EnviornmentalMode.cpp.i
.PHONY : src/EnviornmentalMode.i

# target to preprocess a source file
src/EnviornmentalMode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/EnviornmentalMode.cpp.i
.PHONY : src/EnviornmentalMode.cpp.i

src/EnviornmentalMode.s: src/EnviornmentalMode.cpp.s
.PHONY : src/EnviornmentalMode.s

# target to generate assembly for a file
src/EnviornmentalMode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/EnviornmentalMode.cpp.s
.PHONY : src/EnviornmentalMode.cpp.s

src/GUI.o: src/GUI.cpp.o
.PHONY : src/GUI.o

# target to build an object file
src/GUI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/GUI.cpp.o
.PHONY : src/GUI.cpp.o

src/GUI.i: src/GUI.cpp.i
.PHONY : src/GUI.i

# target to preprocess a source file
src/GUI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/GUI.cpp.i
.PHONY : src/GUI.cpp.i

src/GUI.s: src/GUI.cpp.s
.PHONY : src/GUI.s

# target to generate assembly for a file
src/GUI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/GUI.cpp.s
.PHONY : src/GUI.cpp.s

src/Game.o: src/Game.cpp.o
.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i
.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s
.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/GameState.o: src/GameState.cpp.o
.PHONY : src/GameState.o

# target to build an object file
src/GameState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/GameState.cpp.o
.PHONY : src/GameState.cpp.o

src/GameState.i: src/GameState.cpp.i
.PHONY : src/GameState.i

# target to preprocess a source file
src/GameState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/GameState.cpp.i
.PHONY : src/GameState.cpp.i

src/GameState.s: src/GameState.cpp.s
.PHONY : src/GameState.s

# target to generate assembly for a file
src/GameState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/GameState.cpp.s
.PHONY : src/GameState.cpp.s

src/GraphicsSettings.o: src/GraphicsSettings.cpp.o
.PHONY : src/GraphicsSettings.o

# target to build an object file
src/GraphicsSettings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/GraphicsSettings.cpp.o
.PHONY : src/GraphicsSettings.cpp.o

src/GraphicsSettings.i: src/GraphicsSettings.cpp.i
.PHONY : src/GraphicsSettings.i

# target to preprocess a source file
src/GraphicsSettings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/GraphicsSettings.cpp.i
.PHONY : src/GraphicsSettings.cpp.i

src/GraphicsSettings.s: src/GraphicsSettings.cpp.s
.PHONY : src/GraphicsSettings.s

# target to generate assembly for a file
src/GraphicsSettings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/GraphicsSettings.cpp.s
.PHONY : src/GraphicsSettings.cpp.s

src/Inventory.o: src/Inventory.cpp.o
.PHONY : src/Inventory.o

# target to build an object file
src/Inventory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Inventory.cpp.o
.PHONY : src/Inventory.cpp.o

src/Inventory.i: src/Inventory.cpp.i
.PHONY : src/Inventory.i

# target to preprocess a source file
src/Inventory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Inventory.cpp.i
.PHONY : src/Inventory.cpp.i

src/Inventory.s: src/Inventory.cpp.s
.PHONY : src/Inventory.s

# target to generate assembly for a file
src/Inventory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Inventory.cpp.s
.PHONY : src/Inventory.cpp.s

src/Lantern.o: src/Lantern.cpp.o
.PHONY : src/Lantern.o

# target to build an object file
src/Lantern.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Lantern.cpp.o
.PHONY : src/Lantern.cpp.o

src/Lantern.i: src/Lantern.cpp.i
.PHONY : src/Lantern.i

# target to preprocess a source file
src/Lantern.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Lantern.cpp.i
.PHONY : src/Lantern.cpp.i

src/Lantern.s: src/Lantern.cpp.s
.PHONY : src/Lantern.s

# target to generate assembly for a file
src/Lantern.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Lantern.cpp.s
.PHONY : src/Lantern.cpp.s

src/Level.o: src/Level.cpp.o
.PHONY : src/Level.o

# target to build an object file
src/Level.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Level.cpp.o
.PHONY : src/Level.cpp.o

src/Level.i: src/Level.cpp.i
.PHONY : src/Level.i

# target to preprocess a source file
src/Level.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Level.cpp.i
.PHONY : src/Level.cpp.i

src/Level.s: src/Level.cpp.s
.PHONY : src/Level.s

# target to generate assembly for a file
src/Level.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Level.cpp.s
.PHONY : src/Level.cpp.s

src/Levels.o: src/Levels.cpp.o
.PHONY : src/Levels.o

# target to build an object file
src/Levels.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Levels.cpp.o
.PHONY : src/Levels.cpp.o

src/Levels.i: src/Levels.cpp.i
.PHONY : src/Levels.i

# target to preprocess a source file
src/Levels.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Levels.cpp.i
.PHONY : src/Levels.cpp.i

src/Levels.s: src/Levels.cpp.s
.PHONY : src/Levels.s

# target to generate assembly for a file
src/Levels.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Levels.cpp.s
.PHONY : src/Levels.cpp.s

src/Line.o: src/Line.cpp.o
.PHONY : src/Line.o

# target to build an object file
src/Line.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Line.cpp.o
.PHONY : src/Line.cpp.o

src/Line.i: src/Line.cpp.i
.PHONY : src/Line.i

# target to preprocess a source file
src/Line.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Line.cpp.i
.PHONY : src/Line.cpp.i

src/Line.s: src/Line.cpp.s
.PHONY : src/Line.s

# target to generate assembly for a file
src/Line.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Line.cpp.s
.PHONY : src/Line.cpp.s

src/MainMenuState.o: src/MainMenuState.cpp.o
.PHONY : src/MainMenuState.o

# target to build an object file
src/MainMenuState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/MainMenuState.cpp.o
.PHONY : src/MainMenuState.cpp.o

src/MainMenuState.i: src/MainMenuState.cpp.i
.PHONY : src/MainMenuState.i

# target to preprocess a source file
src/MainMenuState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/MainMenuState.cpp.i
.PHONY : src/MainMenuState.cpp.i

src/MainMenuState.s: src/MainMenuState.cpp.s
.PHONY : src/MainMenuState.s

# target to generate assembly for a file
src/MainMenuState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/MainMenuState.cpp.s
.PHONY : src/MainMenuState.cpp.s

src/NormalTile.o: src/NormalTile.cpp.o
.PHONY : src/NormalTile.o

# target to build an object file
src/NormalTile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/NormalTile.cpp.o
.PHONY : src/NormalTile.cpp.o

src/NormalTile.i: src/NormalTile.cpp.i
.PHONY : src/NormalTile.i

# target to preprocess a source file
src/NormalTile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/NormalTile.cpp.i
.PHONY : src/NormalTile.cpp.i

src/NormalTile.s: src/NormalTile.cpp.s
.PHONY : src/NormalTile.s

# target to generate assembly for a file
src/NormalTile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/NormalTile.cpp.s
.PHONY : src/NormalTile.cpp.s

src/ObjectTile.o: src/ObjectTile.cpp.o
.PHONY : src/ObjectTile.o

# target to build an object file
src/ObjectTile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/ObjectTile.cpp.o
.PHONY : src/ObjectTile.cpp.o

src/ObjectTile.i: src/ObjectTile.cpp.i
.PHONY : src/ObjectTile.i

# target to preprocess a source file
src/ObjectTile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/ObjectTile.cpp.i
.PHONY : src/ObjectTile.cpp.i

src/ObjectTile.s: src/ObjectTile.cpp.s
.PHONY : src/ObjectTile.s

# target to generate assembly for a file
src/ObjectTile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/ObjectTile.cpp.s
.PHONY : src/ObjectTile.cpp.s

src/PauseMenu.o: src/PauseMenu.cpp.o
.PHONY : src/PauseMenu.o

# target to build an object file
src/PauseMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/PauseMenu.cpp.o
.PHONY : src/PauseMenu.cpp.o

src/PauseMenu.i: src/PauseMenu.cpp.i
.PHONY : src/PauseMenu.i

# target to preprocess a source file
src/PauseMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/PauseMenu.cpp.i
.PHONY : src/PauseMenu.cpp.i

src/PauseMenu.s: src/PauseMenu.cpp.s
.PHONY : src/PauseMenu.s

# target to generate assembly for a file
src/PauseMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/PauseMenu.cpp.s
.PHONY : src/PauseMenu.cpp.s

src/PhysicsComponents.o: src/PhysicsComponents.cpp.o
.PHONY : src/PhysicsComponents.o

# target to build an object file
src/PhysicsComponents.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/PhysicsComponents.cpp.o
.PHONY : src/PhysicsComponents.cpp.o

src/PhysicsComponents.i: src/PhysicsComponents.cpp.i
.PHONY : src/PhysicsComponents.i

# target to preprocess a source file
src/PhysicsComponents.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/PhysicsComponents.cpp.i
.PHONY : src/PhysicsComponents.cpp.i

src/PhysicsComponents.s: src/PhysicsComponents.cpp.s
.PHONY : src/PhysicsComponents.s

# target to generate assembly for a file
src/PhysicsComponents.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/PhysicsComponents.cpp.s
.PHONY : src/PhysicsComponents.cpp.s

src/Player.o: src/Player.cpp.o
.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i
.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s
.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/PlayerGUI.o: src/PlayerGUI.cpp.o
.PHONY : src/PlayerGUI.o

# target to build an object file
src/PlayerGUI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/PlayerGUI.cpp.o
.PHONY : src/PlayerGUI.cpp.o

src/PlayerGUI.i: src/PlayerGUI.cpp.i
.PHONY : src/PlayerGUI.i

# target to preprocess a source file
src/PlayerGUI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/PlayerGUI.cpp.i
.PHONY : src/PlayerGUI.cpp.i

src/PlayerGUI.s: src/PlayerGUI.cpp.s
.PHONY : src/PlayerGUI.s

# target to generate assembly for a file
src/PlayerGUI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/PlayerGUI.cpp.s
.PHONY : src/PlayerGUI.cpp.s

src/PlayerGUITabs.o: src/PlayerGUITabs.cpp.o
.PHONY : src/PlayerGUITabs.o

# target to build an object file
src/PlayerGUITabs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/PlayerGUITabs.cpp.o
.PHONY : src/PlayerGUITabs.cpp.o

src/PlayerGUITabs.i: src/PlayerGUITabs.cpp.i
.PHONY : src/PlayerGUITabs.i

# target to preprocess a source file
src/PlayerGUITabs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/PlayerGUITabs.cpp.i
.PHONY : src/PlayerGUITabs.cpp.i

src/PlayerGUITabs.s: src/PlayerGUITabs.cpp.s
.PHONY : src/PlayerGUITabs.s

# target to generate assembly for a file
src/PlayerGUITabs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/PlayerGUITabs.cpp.s
.PHONY : src/PlayerGUITabs.cpp.s

src/SettingsState.o: src/SettingsState.cpp.o
.PHONY : src/SettingsState.o

# target to build an object file
src/SettingsState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/SettingsState.cpp.o
.PHONY : src/SettingsState.cpp.o

src/SettingsState.i: src/SettingsState.cpp.i
.PHONY : src/SettingsState.i

# target to preprocess a source file
src/SettingsState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/SettingsState.cpp.i
.PHONY : src/SettingsState.cpp.i

src/SettingsState.s: src/SettingsState.cpp.s
.PHONY : src/SettingsState.s

# target to generate assembly for a file
src/SettingsState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/SettingsState.cpp.s
.PHONY : src/SettingsState.cpp.s

src/ShaderEditorMode.o: src/ShaderEditorMode.cpp.o
.PHONY : src/ShaderEditorMode.o

# target to build an object file
src/ShaderEditorMode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/ShaderEditorMode.cpp.o
.PHONY : src/ShaderEditorMode.cpp.o

src/ShaderEditorMode.i: src/ShaderEditorMode.cpp.i
.PHONY : src/ShaderEditorMode.i

# target to preprocess a source file
src/ShaderEditorMode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/ShaderEditorMode.cpp.i
.PHONY : src/ShaderEditorMode.cpp.i

src/ShaderEditorMode.s: src/ShaderEditorMode.cpp.s
.PHONY : src/ShaderEditorMode.s

# target to generate assembly for a file
src/ShaderEditorMode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/ShaderEditorMode.cpp.s
.PHONY : src/ShaderEditorMode.cpp.s

src/SkillComponent.o: src/SkillComponent.cpp.o
.PHONY : src/SkillComponent.o

# target to build an object file
src/SkillComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/SkillComponent.cpp.o
.PHONY : src/SkillComponent.cpp.o

src/SkillComponent.i: src/SkillComponent.cpp.i
.PHONY : src/SkillComponent.i

# target to preprocess a source file
src/SkillComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/SkillComponent.cpp.i
.PHONY : src/SkillComponent.cpp.i

src/SkillComponent.s: src/SkillComponent.cpp.s
.PHONY : src/SkillComponent.s

# target to generate assembly for a file
src/SkillComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/SkillComponent.cpp.s
.PHONY : src/SkillComponent.cpp.s

src/State.o: src/State.cpp.o
.PHONY : src/State.o

# target to build an object file
src/State.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/State.cpp.o
.PHONY : src/State.cpp.o

src/State.i: src/State.cpp.i
.PHONY : src/State.i

# target to preprocess a source file
src/State.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/State.cpp.i
.PHONY : src/State.cpp.i

src/State.s: src/State.cpp.s
.PHONY : src/State.s

# target to generate assembly for a file
src/State.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/State.cpp.s
.PHONY : src/State.cpp.s

src/StatusComponet.o: src/StatusComponet.cpp.o
.PHONY : src/StatusComponet.o

# target to build an object file
src/StatusComponet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/StatusComponet.cpp.o
.PHONY : src/StatusComponet.cpp.o

src/StatusComponet.i: src/StatusComponet.cpp.i
.PHONY : src/StatusComponet.i

# target to preprocess a source file
src/StatusComponet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/StatusComponet.cpp.i
.PHONY : src/StatusComponet.cpp.i

src/StatusComponet.s: src/StatusComponet.cpp.s
.PHONY : src/StatusComponet.s

# target to generate assembly for a file
src/StatusComponet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/StatusComponet.cpp.s
.PHONY : src/StatusComponet.cpp.s

src/Tab.o: src/Tab.cpp.o
.PHONY : src/Tab.o

# target to build an object file
src/Tab.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Tab.cpp.o
.PHONY : src/Tab.cpp.o

src/Tab.i: src/Tab.cpp.i
.PHONY : src/Tab.i

# target to preprocess a source file
src/Tab.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Tab.cpp.i
.PHONY : src/Tab.cpp.i

src/Tab.s: src/Tab.cpp.s
.PHONY : src/Tab.s

# target to generate assembly for a file
src/Tab.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Tab.cpp.s
.PHONY : src/Tab.cpp.s

src/Tile.o: src/Tile.cpp.o
.PHONY : src/Tile.o

# target to build an object file
src/Tile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Tile.cpp.o
.PHONY : src/Tile.cpp.o

src/Tile.i: src/Tile.cpp.i
.PHONY : src/Tile.i

# target to preprocess a source file
src/Tile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Tile.cpp.i
.PHONY : src/Tile.cpp.i

src/Tile.s: src/Tile.cpp.s
.PHONY : src/Tile.s

# target to generate assembly for a file
src/Tile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/Tile.cpp.s
.PHONY : src/Tile.cpp.s

src/TileMap.o: src/TileMap.cpp.o
.PHONY : src/TileMap.o

# target to build an object file
src/TileMap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/TileMap.cpp.o
.PHONY : src/TileMap.cpp.o

src/TileMap.i: src/TileMap.cpp.i
.PHONY : src/TileMap.i

# target to preprocess a source file
src/TileMap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/TileMap.cpp.i
.PHONY : src/TileMap.cpp.i

src/TileMap.s: src/TileMap.cpp.s
.PHONY : src/TileMap.s

# target to generate assembly for a file
src/TileMap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/TileMap.cpp.s
.PHONY : src/TileMap.cpp.s

src/animationComponet.o: src/animationComponet.cpp.o
.PHONY : src/animationComponet.o

# target to build an object file
src/animationComponet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/animationComponet.cpp.o
.PHONY : src/animationComponet.cpp.o

src/animationComponet.i: src/animationComponet.cpp.i
.PHONY : src/animationComponet.i

# target to preprocess a source file
src/animationComponet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/animationComponet.cpp.i
.PHONY : src/animationComponet.cpp.i

src/animationComponet.s: src/animationComponet.cpp.s
.PHONY : src/animationComponet.s

# target to generate assembly for a file
src/animationComponet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/animationComponet.cpp.s
.PHONY : src/animationComponet.cpp.s

src/easylogging++.o: src/easylogging++.cc.o
.PHONY : src/easylogging++.o

# target to build an object file
src/easylogging++.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/easylogging++.cc.o
.PHONY : src/easylogging++.cc.o

src/easylogging++.i: src/easylogging++.cc.i
.PHONY : src/easylogging++.i

# target to preprocess a source file
src/easylogging++.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/easylogging++.cc.i
.PHONY : src/easylogging++.cc.i

src/easylogging++.s: src/easylogging++.cc.s
.PHONY : src/easylogging++.s

# target to generate assembly for a file
src/easylogging++.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/easylogging++.cc.s
.PHONY : src/easylogging++.cc.s

src/hitboxcomponet.o: src/hitboxcomponet.cpp.o
.PHONY : src/hitboxcomponet.o

# target to build an object file
src/hitboxcomponet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/hitboxcomponet.cpp.o
.PHONY : src/hitboxcomponet.cpp.o

src/hitboxcomponet.i: src/hitboxcomponet.cpp.i
.PHONY : src/hitboxcomponet.i

# target to preprocess a source file
src/hitboxcomponet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/hitboxcomponet.cpp.i
.PHONY : src/hitboxcomponet.cpp.i

src/hitboxcomponet.s: src/hitboxcomponet.cpp.s
.PHONY : src/hitboxcomponet.s

# target to generate assembly for a file
src/hitboxcomponet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/hitboxcomponet.cpp.s
.PHONY : src/hitboxcomponet.cpp.s

src/imgui-SFML.o: src/imgui-SFML.cpp.o
.PHONY : src/imgui-SFML.o

# target to build an object file
src/imgui-SFML.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/imgui-SFML.cpp.o
.PHONY : src/imgui-SFML.cpp.o

src/imgui-SFML.i: src/imgui-SFML.cpp.i
.PHONY : src/imgui-SFML.i

# target to preprocess a source file
src/imgui-SFML.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/imgui-SFML.cpp.i
.PHONY : src/imgui-SFML.cpp.i

src/imgui-SFML.s: src/imgui-SFML.cpp.s
.PHONY : src/imgui-SFML.s

# target to generate assembly for a file
src/imgui-SFML.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/imgui-SFML.cpp.s
.PHONY : src/imgui-SFML.cpp.s

src/imgui.o: src/imgui.cpp.o
.PHONY : src/imgui.o

# target to build an object file
src/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/imgui.cpp.o
.PHONY : src/imgui.cpp.o

src/imgui.i: src/imgui.cpp.i
.PHONY : src/imgui.i

# target to preprocess a source file
src/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/imgui.cpp.i
.PHONY : src/imgui.cpp.i

src/imgui.s: src/imgui.cpp.s
.PHONY : src/imgui.s

# target to generate assembly for a file
src/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/imgui.cpp.s
.PHONY : src/imgui.cpp.s

src/imgui_draw.o: src/imgui_draw.cpp.o
.PHONY : src/imgui_draw.o

# target to build an object file
src/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/imgui_draw.cpp.o
.PHONY : src/imgui_draw.cpp.o

src/imgui_draw.i: src/imgui_draw.cpp.i
.PHONY : src/imgui_draw.i

# target to preprocess a source file
src/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/imgui_draw.cpp.i
.PHONY : src/imgui_draw.cpp.i

src/imgui_draw.s: src/imgui_draw.cpp.s
.PHONY : src/imgui_draw.s

# target to generate assembly for a file
src/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/imgui_draw.cpp.s
.PHONY : src/imgui_draw.cpp.s

src/imgui_impl_opengl3.o: src/imgui_impl_opengl3.cpp.o
.PHONY : src/imgui_impl_opengl3.o

# target to build an object file
src/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/imgui_impl_opengl3.cpp.o
.PHONY : src/imgui_impl_opengl3.cpp.o

src/imgui_impl_opengl3.i: src/imgui_impl_opengl3.cpp.i
.PHONY : src/imgui_impl_opengl3.i

# target to preprocess a source file
src/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/imgui_impl_opengl3.cpp.i
.PHONY : src/imgui_impl_opengl3.cpp.i

src/imgui_impl_opengl3.s: src/imgui_impl_opengl3.cpp.s
.PHONY : src/imgui_impl_opengl3.s

# target to generate assembly for a file
src/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/imgui_impl_opengl3.cpp.s
.PHONY : src/imgui_impl_opengl3.cpp.s

src/imgui_stdlib.o: src/imgui_stdlib.cpp.o
.PHONY : src/imgui_stdlib.o

# target to build an object file
src/imgui_stdlib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/imgui_stdlib.cpp.o
.PHONY : src/imgui_stdlib.cpp.o

src/imgui_stdlib.i: src/imgui_stdlib.cpp.i
.PHONY : src/imgui_stdlib.i

# target to preprocess a source file
src/imgui_stdlib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/imgui_stdlib.cpp.i
.PHONY : src/imgui_stdlib.cpp.i

src/imgui_stdlib.s: src/imgui_stdlib.cpp.s
.PHONY : src/imgui_stdlib.s

# target to generate assembly for a file
src/imgui_stdlib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/imgui_stdlib.cpp.s
.PHONY : src/imgui_stdlib.cpp.s

src/imgui_tables.o: src/imgui_tables.cpp.o
.PHONY : src/imgui_tables.o

# target to build an object file
src/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/imgui_tables.cpp.o
.PHONY : src/imgui_tables.cpp.o

src/imgui_tables.i: src/imgui_tables.cpp.i
.PHONY : src/imgui_tables.i

# target to preprocess a source file
src/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/imgui_tables.cpp.i
.PHONY : src/imgui_tables.cpp.i

src/imgui_tables.s: src/imgui_tables.cpp.s
.PHONY : src/imgui_tables.s

# target to generate assembly for a file
src/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/imgui_tables.cpp.s
.PHONY : src/imgui_tables.cpp.s

src/imgui_widgets.o: src/imgui_widgets.cpp.o
.PHONY : src/imgui_widgets.o

# target to build an object file
src/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/imgui_widgets.cpp.o
.PHONY : src/imgui_widgets.cpp.o

src/imgui_widgets.i: src/imgui_widgets.cpp.i
.PHONY : src/imgui_widgets.i

# target to preprocess a source file
src/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/imgui_widgets.cpp.i
.PHONY : src/imgui_widgets.cpp.i

src/imgui_widgets.s: src/imgui_widgets.cpp.s
.PHONY : src/imgui_widgets.s

# target to generate assembly for a file
src/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/imgui_widgets.cpp.s
.PHONY : src/imgui_widgets.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pegasus.dir/build.make CMakeFiles/Pegasus.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Pegasus"
	@echo "... src/BattleGUI.o"
	@echo "... src/BattleGUI.i"
	@echo "... src/BattleGUI.s"
	@echo "... src/BattleState.o"
	@echo "... src/BattleState.i"
	@echo "... src/BattleState.s"
	@echo "... src/Blerb.o"
	@echo "... src/Blerb.i"
	@echo "... src/Blerb.s"
	@echo "... src/Blrb.o"
	@echo "... src/Blrb.i"
	@echo "... src/Blrb.s"
	@echo "... src/CharacterEditorState.o"
	@echo "... src/CharacterEditorState.i"
	@echo "... src/CharacterEditorState.s"
	@echo "... src/CharacterTab.o"
	@echo "... src/CharacterTab.i"
	@echo "... src/CharacterTab.s"
	@echo "... src/DefaultMode.o"
	@echo "... src/DefaultMode.i"
	@echo "... src/DefaultMode.s"
	@echo "... src/DialougeSystem.o"
	@echo "... src/DialougeSystem.i"
	@echo "... src/DialougeSystem.s"
	@echo "... src/EditorModes.o"
	@echo "... src/EditorModes.i"
	@echo "... src/EditorModes.s"
	@echo "... src/EditorState.o"
	@echo "... src/EditorState.i"
	@echo "... src/EditorState.s"
	@echo "... src/Enemy.o"
	@echo "... src/Enemy.i"
	@echo "... src/Enemy.s"
	@echo "... src/EnemyEditorMode.o"
	@echo "... src/EnemyEditorMode.i"
	@echo "... src/EnemyEditorMode.s"
	@echo "... src/EnemySpawner.o"
	@echo "... src/EnemySpawner.i"
	@echo "... src/EnemySpawner.s"
	@echo "... src/EnemySystem.o"
	@echo "... src/EnemySystem.i"
	@echo "... src/EnemySystem.s"
	@echo "... src/Entity.o"
	@echo "... src/Entity.i"
	@echo "... src/Entity.s"
	@echo "... src/EnviornmentalMode.o"
	@echo "... src/EnviornmentalMode.i"
	@echo "... src/EnviornmentalMode.s"
	@echo "... src/GUI.o"
	@echo "... src/GUI.i"
	@echo "... src/GUI.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/GameState.o"
	@echo "... src/GameState.i"
	@echo "... src/GameState.s"
	@echo "... src/GraphicsSettings.o"
	@echo "... src/GraphicsSettings.i"
	@echo "... src/GraphicsSettings.s"
	@echo "... src/Inventory.o"
	@echo "... src/Inventory.i"
	@echo "... src/Inventory.s"
	@echo "... src/Lantern.o"
	@echo "... src/Lantern.i"
	@echo "... src/Lantern.s"
	@echo "... src/Level.o"
	@echo "... src/Level.i"
	@echo "... src/Level.s"
	@echo "... src/Levels.o"
	@echo "... src/Levels.i"
	@echo "... src/Levels.s"
	@echo "... src/Line.o"
	@echo "... src/Line.i"
	@echo "... src/Line.s"
	@echo "... src/MainMenuState.o"
	@echo "... src/MainMenuState.i"
	@echo "... src/MainMenuState.s"
	@echo "... src/NormalTile.o"
	@echo "... src/NormalTile.i"
	@echo "... src/NormalTile.s"
	@echo "... src/ObjectTile.o"
	@echo "... src/ObjectTile.i"
	@echo "... src/ObjectTile.s"
	@echo "... src/PauseMenu.o"
	@echo "... src/PauseMenu.i"
	@echo "... src/PauseMenu.s"
	@echo "... src/PhysicsComponents.o"
	@echo "... src/PhysicsComponents.i"
	@echo "... src/PhysicsComponents.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/PlayerGUI.o"
	@echo "... src/PlayerGUI.i"
	@echo "... src/PlayerGUI.s"
	@echo "... src/PlayerGUITabs.o"
	@echo "... src/PlayerGUITabs.i"
	@echo "... src/PlayerGUITabs.s"
	@echo "... src/SettingsState.o"
	@echo "... src/SettingsState.i"
	@echo "... src/SettingsState.s"
	@echo "... src/ShaderEditorMode.o"
	@echo "... src/ShaderEditorMode.i"
	@echo "... src/ShaderEditorMode.s"
	@echo "... src/SkillComponent.o"
	@echo "... src/SkillComponent.i"
	@echo "... src/SkillComponent.s"
	@echo "... src/State.o"
	@echo "... src/State.i"
	@echo "... src/State.s"
	@echo "... src/StatusComponet.o"
	@echo "... src/StatusComponet.i"
	@echo "... src/StatusComponet.s"
	@echo "... src/Tab.o"
	@echo "... src/Tab.i"
	@echo "... src/Tab.s"
	@echo "... src/Tile.o"
	@echo "... src/Tile.i"
	@echo "... src/Tile.s"
	@echo "... src/TileMap.o"
	@echo "... src/TileMap.i"
	@echo "... src/TileMap.s"
	@echo "... src/animationComponet.o"
	@echo "... src/animationComponet.i"
	@echo "... src/animationComponet.s"
	@echo "... src/easylogging++.o"
	@echo "... src/easylogging++.i"
	@echo "... src/easylogging++.s"
	@echo "... src/hitboxcomponet.o"
	@echo "... src/hitboxcomponet.i"
	@echo "... src/hitboxcomponet.s"
	@echo "... src/imgui-SFML.o"
	@echo "... src/imgui-SFML.i"
	@echo "... src/imgui-SFML.s"
	@echo "... src/imgui.o"
	@echo "... src/imgui.i"
	@echo "... src/imgui.s"
	@echo "... src/imgui_draw.o"
	@echo "... src/imgui_draw.i"
	@echo "... src/imgui_draw.s"
	@echo "... src/imgui_impl_opengl3.o"
	@echo "... src/imgui_impl_opengl3.i"
	@echo "... src/imgui_impl_opengl3.s"
	@echo "... src/imgui_stdlib.o"
	@echo "... src/imgui_stdlib.i"
	@echo "... src/imgui_stdlib.s"
	@echo "... src/imgui_tables.o"
	@echo "... src/imgui_tables.i"
	@echo "... src/imgui_tables.s"
	@echo "... src/imgui_widgets.o"
	@echo "... src/imgui_widgets.i"
	@echo "... src/imgui_widgets.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

